import { Environment } from './environment';

// LOCAL FALLBACK ONLY. In deployed builds this file is regenerated by
// scripts/generate-environment.mjs from Vercel env vars at build time —
// see frontend/package.json `build:vercel` and frontend/vercel.json.
export const environment: Environment = {
  production: true,
  apiUrl: 'https://axiom-api.onrender.com/api',
  sentryDsn: null,
  release: null,
};
