// LOCAL FALLBACK ONLY. In deployed builds this file is regenerated by
// scripts/generate-environment.mjs from Vercel env vars at build time —
// see frontend/package.json `build:vercel` and frontend/vercel.json.
//
// Do not import the Environment interface from ./environment here — Angular's
// fileReplacements substitutes environment.ts with this file at build, which
// would make the import circular. Object-literal inference is enough.
export const environment = {
  production: true,
  apiUrl: 'https://axiom-api.onrender.com/api',
  sentryDsn: null as string | null,
  release: null as string | null,
};
